name: orders_insight
description: "Gain instant insights into your e-commerce performance with key metrics and trend visualizations."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  provider: ^6.1.2
  fl_chart: ^0.69.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: any

flutter:

  uses-material-design: true

  assets:
    - assets/orders.json